MPATH=/share/cs-instructional/cs5220/modules
MODULES=cs5220-base dealii-serial gcc-4.8.2 gperftools \
	ipm julia lapack links llvm llvm-svn \
	lynx mpip openblas openmpi-1.6.5 petsc ploticus \
	slepc sprng sundials tao tau trilinos-serial upc visit \
	anaconda icsxe

.PHONY: install
install:
	install -t $(MPATH) $(MODULES)
