MPATH=$(HOME)/local/modules
MODULES=magma-base dealii-serial gcc-4.9.3 gperftools \
	ipm julia julia-old julia-new lapack llvm llvm-svn \
	mpip openblas openmpi-1.8.6 petsc ploticus R \
	slepc sprng sundials tau trilinos-serial upc visit \
	anaconda icsxe 

.PHONY: install
install:
	install -t $(MPATH) $(MODULES)
