APCPATH=/share/cs-instructional/cs5220

.PHONY: install

install:
	install -d $(APCPATH)/local/etc
	install -d $(APCPATH)/local/bin
	install -t $(APCPATH)/local/etc csubscript
	install -t $(APCPATH)/local/bin csub

