#!/bin/sh

if [ -d "$HOME/.ipython/profile_mpi" ]; then
  echo "HTCondor MPI profile already exists"
  exit 0
fi

ipython profile create --parallel --profile=mpi
PDIR=$HOME/.ipython/profile_mpi

IPENGINE=`which ipengine`
MPISCRIPT=/share/cs-instructional/cs5220/local/openmpi-1.6.5/etc/openmpiscript

cat > $PDIR/batch_submit <<EOF
# HTCondor script generated by ipcluster launcher
universe        = parallel
executable      = $MPISCRIPT
getenv          = true
notification    = never
arguments       = "$HOME $IPENGINE --log-to-file '--profile-dir=$HOME/.ipython/profile_mpi' '--cluster-id='"
requirements    = C4_GROUP == "cs"
machine_count   = {n}
queue
EOF

cat > $PDIR/ipengine_config.py <<EOF
c = get_config()
c.MPI.use = 'mpi4py'
EOF

cat > $PDIR/ipcluster_config.py <<EOF
c = get_config()
c.IPClusterStart.engine_launcher_class = 'HTCondorEngineSetLauncher'
c.HTCondorEngineSetLauncher.batch_template_file = u'$HOME/.ipython/profile_mpi/batch_submit'
EOF

cat > $PDIR/ipcontroller_config.py <<EOF
c = get_config()
c.HubFactory.ip = '*'
EOF

